apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-blue
  labels:
    app: messaging-app
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging-app
      version: blue
  template:
    metadata:
      labels:
        app: messaging-app
        version: blue
    spec:
      containers:
      - name: messaging-app
        image: messaging-app:2.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: MYSQL_DB
          value: "messaging_db"
        - name: MYSQL_USER
          value: "messaging_user"
        - name: MYSQL_PASSWORD
          value: "messaging_password"
        - name: MYSQL_HOST
          value: "db"
        - name: MYSQL_PORT
          value: "3306"
        - name: DJANGO_SECRET_KEY
          value: "your-secret-key-here"
        - name: DEBUG
          value: "1" 