#!/usr/bin/env python3
"""module that calls an async iterator function"""
import asyncio
from typing import List

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Asynchronous coroutine that uses an async comprehension
    to collect 10 random numbers generated by async_generator.

    Returns:
        List[int]: A list containing 10 random integers.
    """
    return [number async for number in async_generator()]
